# kickstart travis.
language: java

before_script:
  - pwd
  - git clone https://github.com/ivanceras/parent
  - cd parent
  - mvn clean install


# need to override travis 'install' since it will try gpg sign and fail.
install: mvn clean install

branches:
  except:
      - mvn-repo
